#!/bin/bash
#PBS -l select=1:ncpus=48:mpiprocs=48
#PBS -l walltime=00:20:00
#PBS -A Project_ID
#PBS -q debug
#PBS -N Job_Array_Test
#PBS -J 0-12:3
#PBS -j oe
#PBS -V
echo "PBS Job Id PBS_JOBID is ${PBS_JOBID}"
echo "PBS job array index PBS_ARRAY_INDEX value is ${PBS_ARRAY_INDEX}"
#
#  To isolate the job id number, cut on the character "[" instead of
#  ".".  PBS_JOBID might look like "48274[].server" rather "48274.server"
#  in job arrays
#
JOBID=`echo ${PBS_JOBID} | cut -d'[' -f1`

#cd $WORKDIR
# Make a directory of the main PBS JOBID

#mkdir ${JOBID}
# go in said directory

#cd ${JOBID}

# Make a subdirectory with the current PBS Job Array Index
#mkdir ${PBS_ARRAY_INDEX}

# Make a variable that has full path to this run
# TMPD might look like this /p/work1/smith/392813/9/
# TMPD=${WORKDIR}/${JOBID}/${PBS_ARRAY_INDEX}

# copy executable or do a module load to get paths to executables
# cp $WORKDIR/picalc.exe ${TMPD}/picalc.exe
# [we assume the presence of a jvm >= 1.8, and a working director like so:

# ./m4-2.24.jar       #base marathon uberjar file
#   batch-test.clj    #our batching facilities
#   batch-script.clj  #job execution clojure script
#   m4-book_AP.xlsx   #pre-supplied input for batch job
#   plan.edn          #pre-supplied runplan for batch job (see batch-test.clj)

# Though not used here, OPTIONAL_INPUT could hold various inputs
# that have different parameters set
# OPTIONAL_INPUT=$WORKDIR/input.${PBS_ARRAY_INDEX}

# cd into directory that will contain all output
## from this PBS_ARRAY_INDEX run
#cd ${TMPD}

# run job and redirect output

#supply the correct jvm args for your node's resources...
#and the correct jar file if using a different version.
java -XX:+UseParallelGC -Xmx250g -jar m4-2.24.jar clojure.main batch_script.clj

#we push all the scripting complexity into the clojure side and handle our
#output generation there.  this should produce multiple batch_{JOBID}_results.txt
#files.  We can alter this behavior by modifying our batch_script.clj script.

exit
